<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Portofolio extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_portfolio' => 2,
                'id_user' => 8,
                'nama_layanan' => ' App Development',
                'id_client' => 6,
                'judul_portfolio' => 'Portfoilo Traveloka',
                'slug_portfolio' => 'portfoilo-traveloka',
                'gambar_portfolio' => 'Traveloka_Primary_Logo.png',
                'isi_portfolio' => "<div>\r\n<div>Lorem,&nbsp;;</div>\r\n</div>",
                'website_portfolio' => 'www.traveloka.com',
                'status_portfolio' => 'Publish',
                'date_created' => '2021-05-02 10:56:38',
                'testimoni' => 'Lorem error.\r\n',
                'last_modified' => '2021-05-02',
                'date_project' => '2021-03-21',
            ],
            [
                'id_portfolio' => 3,
                'id_user' => 8,
                'nama_layanan' => ' Web Development',
                'id_client' => 4,
                'judul_portfolio' => 'Portfolio Gojek',
                'slug_portfolio' => 'portfolio-gojek',
                'gambar_portfolio' => 'hitobajlkseeivcjy22b.png',
                'isi_portfolio' => '<p>Isi portfolio</p>',
                'website_portfolio' => 'www.gojek.com',
                'status_portfolio' => 'Publish',
                'date_created' => '2021-05-02 10:56:33',
                'testimoni' => 'Lorem, alias error.\r\n',
                'last_modified' => '2021-05-02',
                'date_project' => '2021-03-30',
            ],
            [
                'id_portfolio' => 4,
                'id_user' => 8,
                'nama_layanan' => ' Web Development',
                'id_client' => 2,
                'judul_portfolio' => 'Portfolio OVO',
                'slug_portfolio' => 'portfolio-ovo',
                'gambar_portfolio' => '1024px-Logo_ovo_purple_svg.png',
                'isi_portfolio' => "<div>\r\n<div> reprehenderit.</div>\r\n</div>",
                'website_portfolio' => 'www.ovo.com',
                'status_portfolio' => 'Publish',
                'date_created' => '2021-05-02 10:56:27',
                'testimoni' => 'Lorem Quas nemo asperiores doloremque ratione sunt hic obcaecati ut totam pariatur? Molestias voluptas ipsam alias error.\r\n',
                'last_modified' => '2021-05-02',
                'date_project' => '2021-04-25',
            ],
            [
                'id_portfolio' => 5,
                'id_user' => 8,
                'nama_layanan' => 'Web Design',
                'id_client' => 5,
                'judul_portfolio' => 'Portfolio Link Aja',
                'slug_portfolio' => 'portfolio-link-aja',
                'gambar_portfolio' => '1200px-LinkAja_svg.png',
                'isi_portfolio' => '<p>Isi portfolio</p>',
                'website_portfolio' => 'www.linkaja.com',
                'status_portfolio' => 'Publish',
                'date_created' => '2021-05-02 11:14:01',
                'testimoni' => 'ini testimoni link ajah',
                'last_modified' => '2021-05-02',
                'date_project' => '2021-05-20',
            ],
            [
                'id_portfolio' => 6,
                'id_user' => 8,
                'nama_layanan' => ' App Development',
                'id_client' => 8,
                'judul_portfolio' => 'Portfolio Dana',
                'slug_portfolio' => 'portfolio-dana',
                'gambar_portfolio' => '_bjmYta5_400x400.jpg',
                'isi_portfolio' => '<p>Isi portfolio</p>',
                'website_portfolio' => 'www.dana.com',
                'status_portfolio' => 'Publish',
                'date_created' => '2021-05-02 10:56:13',
                'testimoni' => 'Lorem, alias error.\r\n',
                'last_modified' => '2021-05-02',
                'date_project' => '2021-04-02',
            ],
            [
                'id_portfolio' => 7,
                'id_user' => 8,
                'nama_layanan' => 'Web Design',
                'id_client' => 7,
                'judul_portfolio' => 'Portfolio Tokopakedi',
                'slug_portfolio' => 'portfolio-tokopakedi',
                'gambar_portfolio' => '1575050504675-logo-tokopedia.jpg',
                'isi_portfolio' => '<p>Isi portfolio</p>',
                'website_portfolio' => 'www.tokopakedi.com',
                'status_portfolio' => 'Publish',
                'date_created' => '2021-05-02 10:56:03',
                'testimoni' => 'Lorem ratione sunt hic obcaecati ut totam pariatur? Molestias voluptas ipsam alias error.\r\n',
                'last_modified' => '2021-05-02',
                'date_project' => '2021-03-04',
            ],
            [
                'id_portfolio' => 8,
                'id_user' => 8,
                'nama_layanan' => ' App Development',
                'id_client' => 3,
                'judul_portfolio' => 'Portfolio Grab',
                'slug_portfolio' => 'portfolio-grab',
                'gambar_portfolio' => '1200px-Grab_Logo_svg1.png',
                'isi_portfolio' => '<p>Isi portfolio</p>',
                'website_portfolio' => 'www.grab.com',
                'status_portfolio' => 'Publish',
                'date_created' => '2021-05-02 10:55:37',
                'testimoni' => 'Lorem   \r\n',
                'last_modified' => '0000-00-00',
                'date_project' => '2021-03-10',
            ],
            [
                'id_portfolio' => 10,
                'id_user' => 11,
                'nama_layanan' => ' App Development',
                'id_client' => 10,
                'judul_portfolio' => 'Toko Umma',
                'slug_portfolio' => 'toko-umma',
                'gambar_portfolio' => '1752116785_c815d8bdbb4d13c4be6e.png',
                'isi_portfolio' => '<p>cuuuus gassssskeun</p>',
                'website_portfolio' => 'dinkes.situbondokab.go.id',
                'status_portfolio' => 'Publish',
                'date_created' => '2025-07-10 10:16:55',
                'testimoni' => 'Luar biasa bagus sekali',
                'last_modified' => '2025-07-10',
                'date_project' => '2025-07-10',
            ],
        ];

        $this->db->table('tb_portfolio')->insertBatch($data);
    }
}
